"""
Ollama Metrics Exporter + Transparent Proxy
============================================
:9110/metrics  — Prometheus metrics endpoint
:11435          — Transparent proxy to Ollama (intercepts every request to collect stats)

How it works:
  Apps (backend, copilot, automation) point OLLAMA_HOST to this container on :11435.
  Every /api/generate and /api/chat call is forwarded to real Ollama (:11434).
  The final streaming chunk always contains eval_count / prompt_eval_count / total_duration.
  Those are recorded as Prometheus counters/histograms before the chunk is forwarded.
"""
import json, os, time, threading
from http.server import HTTPServer, BaseHTTPRequestHandler, ThreadingHTTPServer
import requests
from prometheus_client import (
    Counter, Histogram, Gauge, Info,
    generate_latest, CONTENT_TYPE_LATEST, REGISTRY,
)

OLLAMA_BASE     = os.environ.get("OLLAMA_BASE_URL", "http://NETAct_ollama:11434")
METRICS_PORT    = int(os.environ.get("METRICS_PORT", "9110"))
PROXY_PORT      = int(os.environ.get("PROXY_PORT", "11435"))
POLL_INTERVAL   = 15   # seconds between /api/ps + /api/tags polls

# ── Prometheus metrics ──────────────────────────────────────────────────────

ollama_up = Gauge("ollama_up", "1 if Ollama API is reachable, 0 otherwise")
ollama_info = Info("ollama", "Ollama version information")

models_available = Gauge("ollama_models_available", "Number of models stored on disk")
model_size       = Gauge("ollama_model_size_bytes",
                         "Disk size of model in bytes",
                         ["model", "family", "quantization"])

models_loaded    = Gauge("ollama_models_loaded", "Number of models currently in memory")
model_vram       = Gauge("ollama_model_vram_bytes", "VRAM used by loaded model", ["model"])
model_ram        = Gauge("ollama_model_ram_bytes",  "RAM used by loaded model",  ["model"])
model_expires    = Gauge("ollama_model_expires_unix", "Unix timestamp when model unloads", ["model"])

# Proxy-collected metrics
request_duration = Histogram(
    "ollama_request_duration_seconds",
    "End-to-end request duration (from Ollama total_duration field)",
    ["model", "endpoint"],
    buckets=[0.1, 0.5, 1, 2, 5, 10, 20, 30, 60, 120],
)
tokens_generated = Counter(
    "ollama_tokens_generated_total",
    "Total output tokens generated by model",
    ["model"],
)
prompt_tokens = Counter(
    "ollama_prompt_tokens_total",
    "Total prompt (input) tokens processed by model",
    ["model"],
)
requests_total = Counter(
    "ollama_requests_total",
    "Total LLM requests proxied",
    ["model", "endpoint", "status"],
)
tokens_per_second = Gauge(
    "ollama_tokens_per_second",
    "Token generation rate for the most recent request",
    ["model"],
)

# ── Background poller ───────────────────────────────────────────────────────

def safe_get(path):
    try:
        r = requests.get(f"{OLLAMA_BASE}{path}", timeout=5)
        r.raise_for_status()
        return r.json()
    except Exception as e:
        print(f"[poll] GET {path} failed: {e}")
        return None


def poll_loop():
    while True:
        try:
            ver = safe_get("/api/version")
            if ver:
                ollama_up.set(1)
                ollama_info.info({"version": ver.get("version", "unknown")})
            else:
                ollama_up.set(0)

            tags = safe_get("/api/tags")
            model_list = (tags or {}).get("models", [])
            models_available.set(len(model_list))
            for m in model_list:
                name  = m.get("name", "unknown")
                fam   = m.get("details", {}).get("family", "unknown")
                quant = m.get("details", {}).get("quantization_level", "unknown")
                model_size.labels(model=name, family=fam, quantization=quant).set(m.get("size", 0))

            ps = safe_get("/api/ps")
            running = (ps or {}).get("models", [])
            models_loaded.set(len(running))
            for m in running:
                name  = m.get("name", "unknown")
                size  = m.get("size", 0)
                vram  = m.get("size_vram", 0)
                model_vram.labels(model=name).set(vram)
                model_ram.labels(model=name).set(size - vram)
                expires = m.get("expires_at", "")
                try:
                    from datetime import datetime
                    ts = datetime.fromisoformat(expires.replace("Z", "+00:00")).timestamp()
                except Exception:
                    ts = 0
                model_expires.labels(model=name).set(ts)

        except Exception as e:
            print(f"[poll] error: {e}")

        time.sleep(POLL_INTERVAL)


# ── Proxy handler ───────────────────────────────────────────────────────────

TRACKED_PATHS = {"/api/generate", "/api/chat", "/api/embeddings"}


class ProxyHandler(BaseHTTPRequestHandler):

    def _proxy(self):
        content_len = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_len) if content_len else b""

        path = self.path
        is_llm = any(path.startswith(p) for p in TRACKED_PATHS)

        # Extract model name and estimate prompt tokens from request body
        req_model = "unknown"
        est_prompt_tokens = 0
        if is_llm and body:
            try:
                parsed_body = json.loads(body)
                req_model = parsed_body.get("model", "unknown")
                prompt_text = parsed_body.get("prompt") or parsed_body.get("input")
                if isinstance(prompt_text, list):
                    prompt_text = " ".join(str(x) for x in prompt_text)
                if prompt_text and isinstance(prompt_text, str):
                    est_prompt_tokens = max(1, len(prompt_text) // 4)
            except Exception:
                pass

        start_wall = time.time()

        try:
            fwd_headers = {
                k: v for k, v in self.headers.items()
                if k.lower() not in ("host", "content-length", "transfer-encoding", "accept-encoding")
            }
            upstream = requests.request(
                self.command,
                f"{OLLAMA_BASE}{path}",
                headers=fwd_headers,
                data=body,
                stream=True,
                timeout=600,
            )

            self.send_response(upstream.status_code)
            for k, v in upstream.headers.items():
                if k.lower() not in ("transfer-encoding", "content-encoding", "content-length"):
                    self.send_header(k, v)
            self.end_headers()

            last_chunk_data = None

            if is_llm:
                # Stream line-by-line so we can inspect the final "done" chunk
                for raw_line in upstream.iter_lines(chunk_size=64):
                    if raw_line:
                        self.wfile.write(raw_line + b"\n")
                        try:
                            self.wfile.flush()
                        except Exception:
                            break
                        try:
                            last_chunk_data = json.loads(raw_line)
                        except Exception:
                            pass
            else:
                # Non-LLM paths: stream raw bytes
                for chunk in upstream.iter_content(chunk_size=8192):
                    self.wfile.write(chunk)

            # Record metrics from final chunk or non-streaming embeddings endpoints
            if is_llm and last_chunk_data:
                m = last_chunk_data.get("model", req_model)
                is_embedding = any(x in path for x in ("/api/embeddings", "/api/embed"))
                
                if is_embedding or last_chunk_data.get("done"):
                    eval_c     = last_chunk_data.get("eval_count", 0)
                    prompt_c   = last_chunk_data.get("prompt_eval_count", 0)
                    total_dur  = last_chunk_data.get("total_duration", 0) / 1e9   # ns → s
                    eval_dur   = last_chunk_data.get("eval_duration", 0) / 1e9    # ns → s

                    dur_observed = total_dur if total_dur > 0 else (time.time() - start_wall)
                    request_duration.labels(model=m, endpoint=path).observe(dur_observed)
                    
                    if eval_c > 0:
                        tokens_generated.labels(model=m).inc(eval_c)
                    
                    actual_prompt_c = prompt_c if prompt_c > 0 else est_prompt_tokens
                    if actual_prompt_c > 0:
                        prompt_tokens.labels(model=m).inc(actual_prompt_c)
                        
                    requests_total.labels(
                        model=m, endpoint=path, status=str(upstream.status_code)
                    ).inc()
                    if eval_dur > 0 and eval_c > 0:
                        tokens_per_second.labels(model=m).set(eval_c / eval_dur)

        except Exception as e:
            print(f"[proxy] {self.command} {path} → error: {e}")
            try:
                requests_total.labels(
                    model=req_model, endpoint=path, status="error"
                ).inc()
            except Exception:
                pass

    def do_GET(self):    self._proxy()
    def do_POST(self):   self._proxy()
    def do_DELETE(self): self._proxy()
    def do_HEAD(self):   self._proxy()

    def log_message(self, fmt, *args):
        # Only log LLM calls, skip noisy health pings
        if any(p in self.path for p in ("/api/generate", "/api/chat")):
            print(f"[proxy] {self.address_string()} {fmt % args}")


# ── Metrics handler ─────────────────────────────────────────────────────────

class MetricsHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path not in ("/metrics", "/"):
            self.send_response(404); self.end_headers(); return
        body = generate_latest(REGISTRY)
        self.send_response(200)
        self.send_header("Content-Type", CONTENT_TYPE_LATEST)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *_):
        pass


# ── Entry point ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    # Start background poller
    threading.Thread(target=poll_loop, daemon=True).start()

    # Start metrics HTTP server in background thread
    metrics_srv = HTTPServer(("0.0.0.0", METRICS_PORT), MetricsHandler)
    threading.Thread(target=metrics_srv.serve_forever, daemon=True).start()
    print(f"[metrics] listening on :{METRICS_PORT}")

    # Start proxy (blocks main thread)
    proxy_srv = ThreadingHTTPServer(("0.0.0.0", PROXY_PORT), ProxyHandler)
    print(f"[proxy]   listening on :{PROXY_PORT}  →  {OLLAMA_BASE}")
    proxy_srv.serve_forever()
